name: base_app_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  flutter_lints: ^2.0.0
  get: ^4.6.5
  http: ^0.13.5
  shared_preferences: ^2.0.15
  scrollable_positioned_list: ^0.3.5
  fluttertoast: ^8.0.9
  flutter_svg: ^2.0.0
  carousel_slider: ^4.1.1
  scroll_snap_list: ^0.9.1
  lottie: ^1.4.3
  flutter_html: ^3.0.0-alpha.6
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.6
  dio: ^4.0.6
  cached_network_image: ^3.2.2
  syncfusion_flutter_datepicker: ^20.4.44
  google_maps_flutter: ^2.2.3
  pusher_client: ^2.0.0
  json_store: ^2.0.1
  webview_flutter: ^4.2.0
  #  flutter_webview_plugin: ^0.4.0
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.0.4
  flutterfire_cli: ^0.2.7
  country_code_picker: ^3.0.0
  pinput: ^2.2.31
  flutter_local_notifications: ^14.0.0+1
  permission_handler: ^10.2.0
#  flutter_widget_from_html: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/animation/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf


