// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG2IQwvtltR_Y6pVBL2SdBalJahLqTE_8',
    appId: '1:63559417054:web:6528f0229ebf1aad69164f',
    messagingSenderId: '63559417054',
    projectId: 'travela-53d75',
    authDomain: 'travela-53d75.firebaseapp.com',
    databaseURL: 'https://travela-53d75-default-rtdb.firebaseio.com',
    storageBucket: 'travela-53d75.appspot.com',
    measurementId: 'G-C3NJFJWBWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_BbO07oKPwPwkaClBRCKJV3zAKf2XBZk',
    appId: '1:63559417054:android:5d86e9298de6561969164f',
    messagingSenderId: '63559417054',
    projectId: 'travela-53d75',
    databaseURL: 'https://travela-53d75-default-rtdb.firebaseio.com',
    storageBucket: 'travela-53d75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzmzn3xaAdopTjuo_4AIGXQ4MSag3UvjY',
    appId: '1:63559417054:ios:0cf8b35dd556c4a869164f',
    messagingSenderId: '63559417054',
    projectId: 'travela-53d75',
    databaseURL: 'https://travela-53d75-default-rtdb.firebaseio.com',
    storageBucket: 'travela-53d75.appspot.com',
    androidClientId: '63559417054-9bvjaqq1f5soshsqagt1gk612qhquebu.apps.googleusercontent.com',
    iosClientId: '63559417054-mddjs9mnk36pfqs526taa7qjdvkq93oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzmzn3xaAdopTjuo_4AIGXQ4MSag3UvjY',
    appId: '1:63559417054:ios:0cf8b35dd556c4a869164f',
    messagingSenderId: '63559417054',
    projectId: 'travela-53d75',
    databaseURL: 'https://travela-53d75-default-rtdb.firebaseio.com',
    storageBucket: 'travela-53d75.appspot.com',
    androidClientId: '63559417054-9bvjaqq1f5soshsqagt1gk612qhquebu.apps.googleusercontent.com',
    iosClientId: '63559417054-mddjs9mnk36pfqs526taa7qjdvkq93oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseAppFlutter',
  );
}
